#!/bin/bash
date;
for i in ` netstat -tanpu | grep "SYN_RECV" | awk {'print $5'} | cut -f 1 -d ":" | sort | uniq -c | sort -n | awk {'if ($1 > 3) print $2'}` ; 
do
geoiplookup $i >> /root/backup/geoipblocker.txt;
action1="`tail -n 1 /root/backup/geoipblocker.txt`"

if [[ $action1 = "GeoIP Country Edition: US, United States" ]] || [[ $action1 = "GeoIP Country Edition: IP Address not found" ]] || [[ $action1 = "GeoIP Country Edition: DE, Germany" ]] || [[ $action1 = "GeoIP Country Edition: KW, Kuwait" ]]
   then		
	echo "$i is not OK $action1 >> BLOCKED"
        /sbin/iptables -A INPUT -s $i -j DROP
   else 
          echo "$i is OK"
  fi
done
